# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 02:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '\u4e2a\u4eba\u4f5c\u54c1'), (1, '\u8f6c\u8f7d')], default=0, verbose_name='\u6587\u7ae0\u6765\u6e90')),
                ('title', models.CharField(max_length=30, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('summary', models.TextField(max_length=200, verbose_name='\u6587\u7ae0\u6458\u8981')),
                ('body', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('img_link', models.CharField(max_length=255, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('views', models.IntegerField(default=0, verbose_name='\u9605\u89c8\u91cf')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Category')),
                ('tags', models.ManyToManyField(related_name='tags', to='blog.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
            },
        ),
    ]
